### ISSUE TITLE
example data path

### ISSUE THREAD

**Issue by travisnmiles** [c-proof/pyglider#172]
When running the getting started: Slocum code
```
 import pyglider.example_data as pexamp

pexamp.get_example_data('./') pyglider/example_data.py 
```

the data download fails as I believe the web address in example_data is no longer correct [https://cproof.uvic.ca/pyglider-example-data/](url)

**Comment by jklymak** [comment]
Thanks, I think this is fixed now, but we do need a better solution, so I've changed the title.

**Comment by ecastrillo** [comment]
Hi!

Still getting the error:

`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cproof.uvic.ca/pyglider-example-data/pyglider-example-data.zip`

![image](https://github.com/user-attachments/assets/bd32be7c-7435-43c6-b41c-a89752b404b0)

Checked for changes in the file [example_data.py](https://github.com/c-proof/pyglider/blob/main/pyglider/example_data.py), but I can't see any. Am I looking in the wrong direction?

The example data is supposed to be the same as in the github repo [pyglider-example-data](https://github.com/c-proof/pyglider-example-data)?

**Comment by jklymak** [comment]
Sorry, changed servers and that didn't get moved.  Thanks.  

The data is the same as the repo.
